name: Agenda creation test and debug 

on:
  push:
  schedule:
    - cron: '0 0 * * 4' # Runs at midnight UTC on Thursday

env:
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Python
      run: pip3 install pipenv && pipenv install --dev

    - name: Test Python
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: make test-python
      
    - name: Debug Agenda Creation
      if: ${{ github.ref == 'refs/heads/main' }}
      run: make debug
