name: Agenda notification test

on:
  push:
  schedule:
    - cron: '0 2 * * 5' # Runs at 2am UTC on Friday 
  workflow_dispatch: # manual trigger

env:
  TEST_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TEST_USER_AUTH_CODE: ${{ secrets.USER_AUTH_CODE }}
  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Python
      run: pip3 install pipenv && pipenv install --dev

    - name: Test Python
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: make test-python
      
    - name: Test Agenda Notification
      if: ${{ github.ref == 'refs/heads/main' && env.TEST_USER_AUTH_CODE != '' && github.event_name == 'workflow_dispatch'}}
      run: |
        echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > .env
        echo "export LOGURU_LEVEL=DEBUG" >> .env
        echo "export USER_AUTH_CODE=$TEST_USER_AUTH_CODE" >> .env 
        make test-agenda-notify

    - name: Test Agenda Webhook Notification
      if: ${{ github.ref == 'refs/heads/main' && env.TEAMS_WEBHOOK_URL != '' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
      run: |
        echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > .env
        echo "export LOGURU_LEVEL=DEBUG" >> .env
        echo "export TEAMS_WEBHOOK_URL=${{ env.TEAMS_WEBHOOK_URL }}" >> .env 
        make test-agenda-notify
