name: Agenda creation test 

on:
  schedule:
    - cron: '0 3 * * 5' # Runs at midnight UTC on Friday 
  workflow_dispatch: # manual trigger
  workflow_run:
    workflows: [Weekly meeting plan sync test]
    types:
      - completed
    branches:
      - main
env:
  TEST_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Python
      run: pip3 install pipenv && pipenv install --dev

    - name: Test Agenda Creation
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > .env
        echo "export LOGURU_LEVEL=DEBUG" >> .env
        make test-agenda-create
