name: Agenda creation test 

on:
  schedule:
    - cron: '0 0 * * 5' # Runs at midnight UTC on Friday 
  workflow_run:
    workflows: ["Weekly meeting plan sync test"]
    types: [requested]
    branches-ignore:
      - "main"
env:
  TEST_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Python
      run: pip3 install pipenv && pipenv install --dev

    - name: Test Python
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: make test-python
      
    - name: Test Agenda Creation
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > .env
        echo "export LOGURU_LEVEL=DEBUG" >> .env
        make test-agenda-create
