name: Agenda creation test and debug 

on:
  push:
  schedule:
    - cron: '0 0 * * 5' # Runs at midnight UTC on Friday 

env:
  TEST_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TEST_USER_AUTH_CODE: ${{ secrets.USER_AUTH_CODE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Python
      run: pip3 install pipenv && pipenv install --dev

    - name: Test Python
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: make test-python
      
    - name: Test Agenda Creation
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > test.env
        echo "export LOGURU_LEVEL=DEBUG" >> test.env
        echo "export USER_AUTH_CODE=$TEST_USER_AUTH_CODE" >> test.env 
        make test
