name: Weekly meeting plan sync test

on:
  schedule:
    - cron: '0 23 * * 3,4,5,6,0,1' # Runs at 10pm UTC on Wednesday through Monday every week
  workflow_dispatch: # manual trigger
env:
  TEST_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare Python
        run: pip3 install pipenv && pipenv install --dev
        
      - name: Test Weekly Meeting Signup Sync
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "export CLIENT_SECRET=$TEST_CLIENT_SECRET" > .env
          echo "export LOGURU_LEVEL=DEBUG" >> .env
          make test-sync-signup
